name: Run Jest Tests

# Trigger on push and pull_request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  
  pull-requests: write
  id-token: write  

jobs:
  test:
    runs-on: ubuntu-latest  

    # MongoDB service for database-dependent tests
    services:
      mongodb:
        image: mongo:latest  
        ports:
          - 27017:27017  

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Cache npm dependencies for faster runs

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests
        run: npx jest test/register.test.js
        env:
          MONGO_URI: mongodb://localhost:27017/testdb